# Base configs
#baseurl: "https://photography.rampatra.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "HeroVisio by Hero"
subtitle: "A simple vision!"
author: "Hero"
header:
 title: "HeroVisio"
 subtitle: "by Hero"
footer:
 name: "Hey there, my name is Hero."
 bio: "I am a photography enthusiast, I love capturing the landscapes, moments and streets of the places I visit."

web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  #twitter: "https://www.twitter.com/herovisio"
  instagram: "https://www.instagram.com/herovisio"
  #dribbble: "https://dribbble.com/herovisio"
  #linkedin: "https://in.linkedin.com/in/herovisio"
  #github: "https://www.github.com/herovisio"
